import React, { useEffect } from 'react';
import { motion } from 'motion/react';
import { BarChart3, X, Zap, CheckCircle2, Loader2, Hourglass, ShieldCheck } from 'lucide-react';

export const Loading = ({ onComplete }: { onComplete: () => void }) => {
  useEffect(() => {
    const timer = setTimeout(onComplete, 3000);
    return () => clearTimeout(timer);
  }, [onComplete]);

  return (
    <motion.div 
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="fixed inset-0 z-50 flex flex-col items-center justify-center bg-primary"
    >
      <header className="absolute top-0 left-0 w-full flex items-center justify-between px-6 py-6 md:px-12">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 bg-slate-900 rounded-full flex items-center justify-center text-primary">
            <BarChart3 className="w-5 h-5" />
          </div>
          <h2 className="text-slate-900 font-extrabold text-xl tracking-tighter">Credit_IQ</h2>
        </div>
        <div className="flex items-center gap-4">
          <span className="text-slate-900/60 text-sm font-semibold tracking-wide uppercase">Processing Request</span>
          <button className="w-10 h-10 bg-white/20 backdrop-blur-md rounded-full flex items-center justify-center text-slate-900">
            <X className="w-5 h-5" />
          </button>
        </div>
      </header>

      <div className="relative flex flex-col items-center justify-center">
        <div className="absolute w-96 h-96 bg-white/30 rounded-full blur-3xl opacity-50"></div>
        <div className="animate-float relative z-10 w-64 md:w-80 h-64 md:h-80 rounded-full bg-white/40 backdrop-blur-xl border border-white/60 flex items-center justify-center overflow-hidden shadow-2xl">
          <div className="absolute inset-0 bg-gradient-to-tr from-white/20 to-transparent"></div>
          <div className="relative flex flex-col items-center">
            <Zap className="w-16 h-16 text-slate-900 opacity-80 mb-2 fill-slate-900" />
            <div className="flex gap-1">
              <div className="w-1.5 h-1.5 bg-slate-900 rounded-full animate-bounce [animation-delay:-0.3s]"></div>
              <div className="w-1.5 h-1.5 bg-slate-900 rounded-full animate-bounce [animation-delay:-0.15s]"></div>
              <div className="w-1.5 h-1.5 bg-slate-900 rounded-full animate-bounce"></div>
            </div>
          </div>
        </div>

        <div className="mt-12 flex flex-col items-center gap-6 text-center px-6 max-w-md">
          <div className="space-y-1">
            <h1 className="text-3xl font-extrabold tracking-tight text-slate-900">Extracting raw tables...</h1>
            <p className="text-lg font-medium opacity-90 italic text-slate-900/70">Scraping MCA21 V3...</p>
          </div>
          <div className="w-full h-1.5 bg-slate-900/10 rounded-full overflow-hidden">
            <motion.div 
              initial={{ width: 0 }}
              animate={{ width: '66%' }}
              transition={{ duration: 2 }}
              className="h-full bg-slate-900 rounded-full"
            />
          </div>
          <div className="flex flex-col gap-3 w-full">
            <div className="flex items-center gap-3 px-4 py-3 rounded-xl bg-white/40 backdrop-blur-sm border border-white/20">
              <CheckCircle2 className="w-5 h-5 text-emerald-700" />
              <p className="text-slate-900 text-sm font-semibold">Auth verification complete</p>
            </div>
            <div className="flex items-center gap-3 px-4 py-3 rounded-xl bg-white/60 backdrop-blur-sm border border-white/30">
              <Loader2 className="w-5 h-5 text-slate-900 animate-spin" />
              <p className="text-slate-900 text-sm font-semibold">Simulating Credit Committee...</p>
            </div>
            <div className="flex items-center gap-3 px-4 py-3 rounded-xl bg-white/20 backdrop-blur-sm opacity-60">
              <Hourglass className="w-5 h-5 text-slate-900" />
              <p className="text-slate-900 text-sm font-semibold">Finalizing risk score</p>
            </div>
          </div>
        </div>
      </div>

      <div className="absolute bottom-12 left-12 flex items-center gap-4 hidden lg:flex">
        <div className="w-12 h-12 rounded-lg bg-slate-900/10 backdrop-blur-md flex items-center justify-center">
          <ShieldCheck className="w-6 h-6 text-slate-900" />
        </div>
        <div className="text-slate-900">
          <p className="text-[10px] uppercase tracking-widest font-bold opacity-60">Security Protocol</p>
          <p className="text-xs font-mono font-bold">AES-256 ACTIVE</p>
        </div>
      </div>
      <div className="absolute bottom-12 right-12 text-right hidden lg:block">
        <p className="text-slate-900/40 text-[10px] uppercase tracking-[0.2em] font-bold mb-1">Generated by AI Engines</p>
        <p className="text-slate-900 font-extrabold text-sm">Credit_IQ v2.0.4-PRO</p>
      </div>
    </motion.div>
  );
};
